'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
sum = 2

prevTerm = 1
currTerm = 2
nextTerm = 0

while prevTerm + currTerm <= 4000001:
    nextTerm = prevTerm + currTerm
    prevTerm = currTerm
    currTerm = nextTerm
    if nextTerm % 2 == 0:
        sum += nextTerm

print(sum)
